### ISSUE TITLE
new GUI: File menu could have also "brower folder"

### ISSUE THREAD

**Issue by lindemann09** [expyriment/DIF#7]

**Comment by fladd** [comment]
I think no, because the "Browse" button is not a global file action, but its function is merely to fill the local entry field to the left of it with content.

If the concern is about keyboard shortcuts (since the file menu items are accessible via shortcuts): The browse button has focus by default and can hence be directly activated by the space key (and I additionally mapped the more common return key to it). Having selected a directory, the focus is set to the "Generate DIF" button. And after generating, it is set to the "Copy" button. The entire process can hence be entirely keyboard driven if one wants to.

**Comment by lindemann09** [comment]
OK. 

FYI: I deleted to old gui and renamed gui_new.
